export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    REFRESH_TOKEN: '/api/auth/refresh-token',
    CONFIRM_EMAIL: '/api/auth/confirm-email',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    VERIFY_OTP: '/api/auth/verify-otp',
    RESEND_OTP: '/api/auth/resend-otp',
    ME: '/api/auth/me',
  },
  PRODUCTS: {
    LIST: '/api/products',
    DETAIL: (id: string | number) => `/api/products/${id}`,
    BY_NO: (productNo: string) => `/api/products/get-product-by-no/${productNo}`,
    CREATE: '/api/products',
    UPDATE: (id: string | number) => `/api/products/${id}`,
    DELETE: (id: string | number) => `/api/products/${id}`,
  },
  CUSTOMERS: {
    LIST: '/api/customers',
    DETAIL: (username: string) => `/api/customer/${username}`,
    CREATE: '/api/customer',
    DELETE: '/api/customer',
  },
  BASKETS: {
    GET: (username: string) => `/api/baskets/${username}`,
    UPDATE: '/api/baskets',
    DELETE: (username: string) => `/api/baskets/${username}`,
    CHECKOUT: '/api/baskets/checkout',
  },
  ORDERS: {
    LIST: '/api/v1/orders',
    BY_USER: (username: string) => `/api/v1/orders/${username}`,
    CREATE: '/api/v1/orders',
    UPDATE: (id: string | number) => `/api/v1/orders/${id}`,
    DELETE: (id: string | number) => `/api/v1/orders/${id}`,
  },
  INVENTORY: {
    STOCK: (itemNo: string) => `/api/inventory/stock/${itemNo}`,
  },
  PAYMENT: {
    CREATE: '/api/payment/create',
    STATUS: (orderNo: string) => `/api/payment/${orderNo}/status`,
    STATUS_BY_CODE: (orderCode: number) => `/api/payment/code/${orderCode}/status`,
    CANCEL: (orderNo: string) => `/api/payment/cancel/${orderNo}`,
    USER: (userId: string) => `/api/payment/user/${userId}`,
    CALLBACK: '/api/payment/payos-callback',
  },
  FLASH_SALE: {
    SESSIONS: '/api/flashsales/sessions',
    ACTIVE_SESSIONS: '/api/flashsales/sessions/active',
    SESSION_DETAIL: (id: number) => `/api/flashsales/sessions/${id}`,
    ACTIVATE_SESSION: (id: number) => `/api/flashsales/sessions/${id}/activate`,
    END_SESSION: (id: number) => `/api/flashsales/sessions/${id}/end`,
    PURCHASE: '/api/flashsales/purchase',
    ITEM_STOCK: (itemId: number) => `/api/flashsales/items/${itemId}/stock`,
    USER_ORDERS: (userName: string) => `/api/flashsales/orders/${userName}`,
  },
  GROUP_BUY: {
    CAMPAIGNS: '/api/groupbuys/campaigns',
    ACTIVE_CAMPAIGNS: '/api/groupbuys/campaigns/active',
    CAMPAIGN_DETAIL: (id: number) => `/api/groupbuys/campaigns/${id}`,
    OPEN_GROUP: '/api/groupbuys/sessions/open',
    JOIN_GROUP: '/api/groupbuys/sessions/join',
    SESSION_BY_CODE: (code: string) => `/api/groupbuys/sessions/invite/${code}`,
  },
} as const;
